<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>WinQuick.Desktop</RootNamespace>
    <AssemblyName>WinQuick.Desktop</AssemblyName>
    <EnableDefaultApplicationDefinition>true</EnableDefaultApplicationDefinition>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../WinQuick.Core/WinQuick.Core.csproj" />
    <ProjectReference Include="../WinQuick.Application/WinQuick.Application.csproj" />
    <ProjectReference Include="../WinQuick.Infrastructure/WinQuick.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>
</Project>
